### ISSUE TITLE
Restoring local log failed

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#3000]
I saw the following exception quite often in our chaos tests, We should adjust our fork such that the exception message more verbose and investigate what is the issue.

```
06:47:37.707 [] [raft-server-raft-atomix-partition-8-state] DEBUG io.zeebe.distributedlog.impl.DefaultDistributedLogstreamService-8 - Restoring local log failed at position 1361506491320, ret
rying.
java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$null$10(NettyMessagingService.java:350) ~[atomix-cluster-3.2.0-alpha4.jar:?]
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) ~[guava-28.0-jre.jar:?]
        at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$null$11(NettyMessagingService.java:350) ~[atomix-cluster-3.2.0-alpha4.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
        at io.atomix.cluster.messaging.impl.AbstractClientConnection$Callback.completeExceptionally(AbstractClientConnection.java:180) ~[atomix-cluster-3.2.0-alpha4.jar:?]
        at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:66) ~[atomix-cluster-3.2.0-alpha4.jar:?]
        at io.atomix.cluster.messaging.impl.AbstractClientConnection.dispatch(AbstractClientConnection.java:39) ~[atomix-cluster-3.2.0-alpha4.jar:?]
        at io.atomix.cluster.messaging.impl.NettyMessagingService$MessageDispatcher.channelRead0(NettyMessagingService.java:827) ~[atomix-cluster-3.2.0-alpha4.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302) ~[netty-codec-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794) ~[netty-transport-native-epoll-4.1.38.Final-linux-x86_64.jar:4.1.38.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424) ~[netty-transport-native-epoll-4.1.38.Final-linux-x86_64.jar:4.1.38.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326) ~[netty-transport-native-epoll-4.1.38.Final-linux-x86_64.jar:4.1.38.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.38.Final.jar:4.1.38.Final]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.atomix.cluster.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
        ... 22 more
```

**Comment by Zelldon** [comment]
I'm still seeing this very frequently in our current chaos cluster. It seems to happen after the cluster is running for a while, maybe related to the fact that it is not ready anymore?

**Comment by MrSaints** [comment]
We encountered this problem too, and we were unable to recover from it without completely removing our statefulset (and PVC). It'd be great to understand the underlying cause a bit more.

**Comment by Zelldon** [comment]
Hi @MrSaints , which version do you use? Have you seen any fail over? Could you share your log?

**Comment by MrSaints** [comment]
@Zelldon 0.21.0-alpha3. Unfortunately, I didn't manage to save the logs before carrying out a fresh re-installation. Prior to the issue however, I was hitting problems with rate limits (?). I was unable to carry out any operations, e.g. cancelling, starting, etc. I decided to give the brokers a quick restart, but when they restarted, that's when I hit this error.

**Comment by deepthidevaki** [comment]
I think this error might be due to the bug fixed in this PR #3147.

**Comment by bhowmikdebarshi** [comment]
Hi, I've seen this same error this morning. Cluster was running for few days without any issue. Today I hit problem with creating new workflow instances. These were failing. I restarted the zeebe nodes, and saw this error. Nodes are still not stable. 

This was cluster status before restart - 

> root@ip-10-35-231-130:/usr/local/zeebe/bin# zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 10.35.234.124:26501
    Partition 1 : Follower
    Partition 2 : Leader
    Partition 3 : Leader
  Broker 1 - 10.35.230.70:26501
    Partition 1 : Leader
    Partition 2 : Follower
    Partition 3 : Follower
  Broker 2 - 10.35.231.130:26501
    Partition 1 : Follower
    Partition 2 : Follower
    Partition 3 : Follower

This is after restart - 

> root@ip-10-35-231-54:/usr/local/zeebe/bin# zbctl status --insecure
Cluster size: 3
Partitions count: 3
Replication factor: 3
Brokers:
  Broker 0 - 10.35.230.236:26501
  Broker 1 - 10.35.231.54:26501
  Broker 2 - 10.35.234.69:26501


Environment:

Version - 0.21.0-alpha-3
Running as docker image.
Embedded Gateway
Elastic Search exporter.
Data folder mounted on external system for all the nodes.

Now I will check if we can recover after completely removing the data folder. 

I've the logs of all three nodes after restart and can share if required. 

Thanks

**Comment by Zelldon** [comment]
Hey @bhowmikdebarshi thanks for the report! 
Could you please try to reproduce with the latest release? (0.22.0-alpha1)
Also be aware that restarting can take some time since the brokers need to reprocess the log.
