### ISSUE TITLE
Java Client can't connect to Camunda Cloud Cluster

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zeebe#4356]
**Describe the bug**
When I try to connect to Camunda Cloud with the Java Client 0.23.0 I get:

```
Caused by: java.io.IOException: Failed while requesting access token with status code 403 and message Forbidden.
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:173)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:125)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.loadCredentials(OAuthCredentialsProvider.java:114)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:72)
	at io.zeebe.client.impl.ZeebeCallCredentials.applyRequestMetadata(ZeebeCallCredentials.java:46)
```

**To Reproduce**
Create a Camunda Cloud Cluster and create to it. 
This code worked in 0.22.1, but does result in the problem with 0.23.0:

```
public class StartWorkflowInstance {

  public static void main(String[] args) {
    ZeebeClient zeebeClient = zeebe();
    
    
    ZeebeFuture<WorkflowInstanceEvent> future = zeebeClient.newCreateInstanceCommand()
      .bpmnProcessId("hello")
      .latestVersion()
      .variables(Collections.singletonMap("someId", "45"))
      .send();
    
    System.out.println(future.join());
  }
  
  
  public static ZeebeClient zeebe() {
    final String clusterUUID = "210b5d9d-717f-4570-90e8-93c0c5922967";
    final String baseUrl = "zeebe.camunda.io";
    final String clientId = "xxx";
    final String clientSecret = "yyy";
    final String authUrl = "https://login.cloud.camunda.io/oauth/token";

    final String broker = clusterUUID + "." + baseUrl + ":443";

    final OAuthCredentialsProviderBuilder c = new OAuthCredentialsProviderBuilder();
    final OAuthCredentialsProvider cred = c.audience(clusterUUID + "." + baseUrl).clientId(clientId)
        .clientSecret(clientSecret).authorizationServerUrl(authUrl).build();

    final ZeebeClientBuilder clientBuilder = ZeebeClient.newClientBuilder() //
    		.brokerContactPoint(broker).credentialsProvider(cred);

    return clientBuilder.build();
  }

}
```

**Environment:**
 - OS: Windows 10
 - Zeebe Version: Camunda Cloud 0.23.0 + Java Client 0.23.0
 - Java:
    ```
    openjdk version "13.0.1" 2019-10-15
    OpenJDK Runtime Environment (build 13.0.1+9)
    OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
    ```

**Comment by pihme** [comment]
Cannot reproduce the issue. I copied the code above, created a new cluster on camunda cloud (the official one, not on ultrawombat). I exchanged the credentials and Ids and was able to connect.

Errror was that it couldn't find a workflow "hello", which is to be expected.

I tested it both with zeebe java client 0.22.2 and 0.23.0 as dependency. Both worked.

**Comment by berndruecker** [comment]
Wired - it is totally reproducible for me :-( I will play around with it a bit more later

**Comment by berndruecker** [comment]
I tried a couple of things:

- Run via Eclipse with JDK8: does not work
- Run on JDK 13 without Eclipse: Works
- Run on JDK 8 without Eclipse: works
- Run on JDK 13 with Eclipse: works
- Run on JDK 8 on Eclipse: works NOW !!!

So I suspect it was some temp file somehwere which now got finally swiped out. 

So I close this issue

**Comment by themichaelscott** [comment]
Same issue, but with no solution to get it to work in 0.23.1.  I upgraded from 0.22.2 and now I get the message 

`
Status{code=CANCELLED, description=null, cause=java.io.IOException: Failed while requesting access token with status code 403 and message Forbidden.
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:173)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:125)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.loadCredentials(OAuthCredentialsProvider.java:114)
	at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.applyCredentials(OAuthCredentialsProvider.java:72)
	at io.zeebe.client.impl.ZeebeCallCredentials.applyRequestMetadata(ZeebeCallCredentials.java:46)`

**Comment by Zelldon** [comment]
Hey @themichaelscott 

on which OS you're running? 
I think you have still a token in a cache. If you're on linux you could try to delete the camunda folder in our home dir ( `~/.camunda`)

Greets
Chris

**Comment by themichaelscott** [comment]
I deleted the cache file, but not the whole directory. I will try that.

**Comment by themichaelscott** [comment]
I deleted the .camunda dir and tried again with no luck.  I didn't catch the error message. I will run again and see if it is the same.

**Comment by themichaelscott** [comment]
Same error message.
`Status{code=CANCELLED, description=null, cause=java.io.IOException: Failed while requesting access token with status code 403 and message Forbidden.... `

**Comment by themichaelscott** [comment]
The call i'm making is a topology request. It runs as I start up my app to make sure I'm configured correctly...
`val credentialsProvider = CredentialsProvider.newCredentialsProviderBuilder()
                .audience(audience)
                .clientId(clientId)
                .clientSecret(clientSecret)
                .authorizationServerUrl(authServerUrl)
                .build()
            client = ZeebeClientBuilderImpl()
                .brokerContactPoint(workflowEngineConfiguration)
                .credentialsProvider(credentialsProvider)
                .build()

            client?.newTopologyRequest()?.send()?.join()`

**Comment by Zelldon** [comment]
What is the content of `audience` and `authServerUrl` ?

**Comment by themichaelscott** [comment]
4e814f95-00f1-41da-85ef-ecf97b88b6ae.zeebe.camunda.io
https://login.cloud.camunda.io/oauth/token

thanks for the help!

**Comment by themichaelscott** [comment]
If it makes a difference, here is what happened. I had a different cluster/client in camunda cloud about 2 months ago.  I didn't use them for a while, but now I'm back and I'm trying to develop against camunda cloud.  I had to create a new cluster/client and I also updated to the 0.23.1 client from 0.22.2.  Not sure if any of that makes a difference.

**Comment by themichaelscott** [comment]
It's late so I am going to sleep for a while. I'll be back in about 4-5 hours.

**Comment by Zelldon** [comment]
Hey mate you can also sleep longer :D 

Could you please verify that you're using the right credentials (clientId and secret) this is often also the cause of these kind of issues.

If this still not works could you please check with the same credentials via zbctl.

So something like:

```
$ export ZEEBE_ADDRESS='4e814f95-00f1-41da-85ef-ecf97b88b6ae.zeebe.camunda.io:443'
$ export ZEEBE_CLIENT_ID='XXXX'
$ export ZEEBE_CLIENT_SECRET='XXXXX'
$ export ZEEBE_AUTHORIZATION_SERVER_URL='https://login.cloud.camunda.io/oauth/token'
$ zbctl status
```
should work I hope.

**Comment by themichaelscott** [comment]
Thanks for the suggestion...
I tried zbctl with the variables and the status call = works
Tried it in my code again - confirmed that all variables are correct = doesn't work

**Comment by themichaelscott** [comment]
![Screen Shot 2020-05-15 at 9 11 31 AM](https://user-images.githubusercontent.com/1562604/82066644-e92f4b00-968c-11ea-8668-c9c6ebd2a571.png)
![Screen Shot 2020-05-15 at 9 14 38 AM](https://user-images.githubusercontent.com/1562604/82066669-f51b0d00-968c-11ea-858d-60fd5940f2bf.png)

**Comment by berndruecker** [comment]
If it is the problem I had it was not about the code or the credentials, it seems to be some wired temp file stored somewhere. Do you have another JDK installed that you could use? The weired thing was that this solved it for me - simply switching JDK's...

You run it from the console - right?

**Comment by themichaelscott** [comment]
No, from the console I was able to hit it. I'm using the java client in my project.  I tried switching which jvm my project was using trying to copy what you did, but I couldn't get it to work.

**Comment by themichaelscott** [comment]
Okay, so I created a small project that built quickly so I could iterate more quickly trying to solve this.  I tried a few different jdks and finally one of them was able to connect to camunda cloud.  Once it worked, my new credentials were saved to my machine and I was able to switch back to my original jdk and it ran successfully.  It's a hack, and I had tried it a few weeks ago without success but when I gave it another shot today, eventually it did work. Thanks!

**Comment by berndruecker** [comment]
Thank you so much for your persistence on this! It is actually a really wired issue.
Do you by any chance remember which JDK was able to connect?

**Comment by themichaelscott** [comment]
JDK 11 generated a new credential file that the JDK 8 is able to use.
I know this now because < 24 hours later, my credentials expired and I have to do it all over again.
There's a bug in the java client and this is not a good work around.  I would think that if I have a valid credential that I'd be able to renew it, but unfortunately that wasn't so.

**Comment by Zelldon** [comment]
@npepinpe I think we probably need to investigate that

**Comment by MiguelPires** [comment]
Hi @themichaelscott, thank you for reporting this issue. 
It seems like that the issue is triggered by some User-Agent values in the OAuth request sent by Zeebe Java client. We can reproduce the successful Java 11 request with:

```
curl -d "audience=44016087-454b-46fe-85cb-c684e7882a44.zeebe.ultrawombat.com&grant_type=client_credentials&client_secret=WqyimihTrLhwcY72Zc2ZUUOwWbQNBz7-hpTrqwsxl0F5CL83MTEZJqqrBNohwlSH&client_id=KKXNEqAvNvYz5yt7pQvX9hAACpV5xIwT" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://login.cloud.ultrawombat.com/oauth/token -A "Java/11.0.7"
```
And also the failing Java 8 request with (the only change is the user-agent value):
```
curl -d "audience=44016087-454b-46fe-85cb-c684e7882a44.zeebe.ultrawombat.com&grant_type=client_credentials&client_secret=WqyimihTrLhwcY72Zc2ZUUOwWbQNBz7-hpTrqwsxl0F5CL83MTEZJqqrBNohwlSH&client_id=KKXNEqAvNvYz5yt7pQvX9hAACpV5xIwT" -H "Content-Type: application/x-www-form-urlencoded" -X POST https://login.cloud.ultrawombat.com/oauth/token -A "Java/1.8.0_252"
```

This seems like an issue with the Cloud environment and I've already contacted the Cloud team so we can fix it. Meanwhile, a workaround that requires no code changes would be to set a JVM option changing the user-agent to something else, like `-Dhttp.agent="other"`.

**Comment by MiguelPires** [comment]
Hey @themichaelscott, the issue should be fixed now. Can you confirm everything is working on your end?

**Comment by themichaelscott** [comment]
Works like a charm. I no longer have the issue on my machine and it's no longer an issue on our pre-production servers.
Thank you so much!!

**Comment by MiguelPires** [comment]
Great, happy to hear that. Please let us know if there's anything else we can help with.

**Comment by shahamit** [comment]
I am still getting similar error message `java.io.IOException: Failed while requesting access token with status code 404 and message Not Found.` when I run my spring boot application. It fails on start up when starting the `zeebeClientLifecycle` bean. The nested error is as stated above.

I am using the below versions of java and libraries
```
                <java.version>11</java.version>
		<spring-zeebe.version>8.0.4</spring-zeebe.version>
		<zeebe.version>8.0.2</zeebe.version>
```
I have started zeebee and other camunda web apps using [this docker-compose file](https://github.com/camunda/camunda-platform/blob/main/docker-compose-core.yaml). 

Is my java application not able to connect to the locally running zeebe cluster? why?

**Comment by berndruecker** [comment]
Could you open a new issue for this, please?
I think you might be suffering from https://github.com/camunda/zeebe/issues/9401 - could you check if you have environment variables set?

**Comment by shahamit** [comment]
Right I will ask this on the camunda forum. My application.properties has this. Do I need to add any more properties?

```
zeebe.client.broker.gatewayAddress=127.0.0.1:26500
zeebe.client.security.plaintext=true
```
